### ISSUE TITLE
Find out original 8 player colors.

### ISSUE THREAD

**Issue by IceReaper** [IceReaper/KKnD#6]

**Comment by spooky** [comment]
Can't be 100% sure because these were measured rather than extracted, but as far as I can tell these are the options provided for selection:
blue: #429cef
red: #de2121
orange: #ff8c00
yellow: #c5a53a
green: #4aef42
aqua: #42efb5
purple: #8c10a5
hotpink: #de008c
dkblue: #42529c
pink: #ff8cad
brown: #7b5221
white: #ceced6
black: #4a4a5a
gold: #ffe652
bronze: #d6a542
